os: linux
version: 0.0



files:
  - source: app.js
    destination: /opt/ccmwc

  - source: package.json
    destination: /opt/ccmwc

  - source: routes
    destination: /opt/ccmwc/routes

  - source: public
    destination: /opt/ccmwc/public



hooks:
  BeforeInstall:
    - location: deployment/BeforeInstall.sh
      runas: root

  AfterInstall:
    - location: deployment/AfterInstall.sh
      runas: root

  ApplicationStart:
    - location: deployment/ApplicationStart.sh
      runas: root