os: linux
version: 0.0



files:
  - source: app.js
    destination: /opt/ccmwc

  - source: package.json
    destination: /opt/ccmwc

  - source: routes.js
    destination: /opt/ccmwc

  - source: api
    destination: /opt/ccmwc/api

  - source: public
    destination: /opt/ccmwc/public

  - source: lib
    destination: /opt/ccmwc/lib



hooks:
  BeforeInstall:
    - location: deployment/BeforeInstall.sh
      runas: root

  AfterInstall:
    - location: deployment/AfterInstall.sh
      runas: root

  ApplicationStart:
    - location: deployment/ApplicationStart.sh
      runas: root