os: linux
version: 0.0



files:
  - source: api
    destination: /opt/ccmwc/api

  - source: app.js
    destination: /opt/ccmwc

  - source: db
    destination: /opt/ccmwc/db
    
  - source: lib
    destination: /opt/ccmwc/lib

  - source: package.json
    destination: /opt/ccmwc

  - source: public
    destination: /opt/ccmwc/public



hooks:
  BeforeInstall:
    - location: deployment/BeforeInstall.sh
      runas: root

  AfterInstall:
    - location: deployment/AfterInstall.sh
      runas: root

  ApplicationStart:
    - location: deployment/ApplicationStart.sh
      runas: root
